version: "3.9"

services:
  workspace:
    container_name: plantree-workspace
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
      args:
        USER_NAME: devuser
        USER_GROUP_NAME: workspace
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/devuser/workspace
    working_dir: /home/devuser/workspace
    ports:
      - 8080:8080
