version: "3.9"

services:
  workspace:
    container_name: plantree-workspace
    env_file: .env
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_GROUP_NAME: ${USER_GROUP_NAME}
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/${USER_NAME}/workspace
    working_dir: /home/${USER_NAME}/workspace
    ports:
      - 8080:8080
