version: "3.9"

services:
  workspace:
    container_name: plantree-workspace
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
      args:
        USER_NAME: devuser
        USER_GROUP_NAME: workspace
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/devuser/workspace
    working_dir: /home/devuser/workspace
    ports:
      - 8080:8080

  db:
    container_name: plantree-db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - type: volume
        source: plantree-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306

volumes:
  plantree-db-volume:
