version: "3.9"

services:
  workspace:
    container_name: plantree-workspace
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
      args:
        USER_NAME: devuser
        USER_GROUP_NAME: workspace
    tty: true
    volumes:
      - type: bind
        source: .
        target: /home/devuser/workspace
    working_dir: /home/devuser/workspace
    ports:
      - 8080:8080

  db:
    container_name: plantree-db
    image: postgres:10
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: dev
    volumes:
      - type: bind
        source: ./.docker/postgres
        target: /var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  dbadmin:
    container_name: plantree-dbadmin
    image: dpage/pgadmin4:6.12
    environment:
      PGADMIN_DEFAULT_EMAIL: dbadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: dbadmin-pass
    volumes:
      - type: bind
        source: ./.docker/pgadmin4
        target: /var/lib/pgadmin
    ports:
      - 8888:80
    restart: always
    depends_on:
      - postgres
