spring:
  # jpa:
  #   database: POSTGRESQL
  #   hibernate:
      # SQL を自動で実行してテーブルを生成する
      # ddl-auto: update
      # show-sql: true

  datasource:
    url: jdbc:mysql://db:3306/dev
    username: dbuser
    password: dbpass
    driver-class-name: com.mysql.cj.jdbc.Driver
