spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      # SQL を自動で実行してテーブルを生成する
      ddl-auto: update
      show-sql: true

  datasource:
    url: jdbc:postgresql://db:5432/dev
    username: dbuser
    password: dbpass
    driver-class-name: org.postgresql.Driver
