name: Build

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Gradle ラッパースクリプトが正しいものか確認する
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: 17
          cache: gradle
      - run: ./gradlew build
